//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingDLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class INZYNIERKA0001 : DbContext
    {
        public INZYNIERKA0001()
            : base("name=INZYNIERKA0001")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RIGHTS> RIGHTS { get; set; }
        public virtual DbSet<ROLES> ROLES { get; set; }
        public virtual DbSet<USERS_DATA> USERS_DATA { get; set; }
        public virtual DbSet<RIGHT_TO_ROLE_VW> RIGHT_TO_ROLE_VW { get; set; }
        public virtual DbSet<USER_DATA_VW> USER_DATA_VW { get; set; }
    }
}
