//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoggingDLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RIGHT_TO_ROLE_VW
    {
        public string right_name { get; set; }
        public string role_name { get; set; }
    }
}
